### ISSUE TITLE
Narrow/Phone View Shows Incorrect Title

### ISSUE THREAD

**Issue by spxis** [apparentvisuals/judo-kata-judge#57]
Currently, when viewing on a larger screen, a Judging screen shows the Judges name in the LHS and the Event Name on the RHS subheader. Reducing the size of the screen, or viewing on a Mobile incorrectly shows the competitor names in place of the Judge on the LHS. 

This means, we lose the name of the Judge, and cannot easily know what Judge the scoring sheet is assigned to.

![image](https://github.com/apparentvisuals/judo-kata-judge/assets/2666255/63873c1b-948b-4c39-bd63-facaf8ad34ec)

vs.

![image](https://github.com/apparentvisuals/judo-kata-judge/assets/2666255/94e0e974-0795-4d72-931f-b7ae6a5f46c8)

**Comment by apparentvisuals** [comment]
fixed
